FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o ware .

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/ware .
COPY --from=builder /app/config.yaml .
EXPOSE 8080
CMD ["./ware"]