services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "!1password"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  db_data: